project_name: ts-node-express
project_description: 'TypeScript Node Starter Project'
repository_url: 'https://github.com/kabirbaidhya/ts-node-express'
branch_url: '{repository_url}/tree/{branch}'
ssh_forward_agent: true
verbose_logging: false

deployment:
  base_dir: /home/app/ts-node-express
  preset: remote-source
  include_files: ['package.json', 'package-lock.json', 'yarn.lock', 'pm2.config.js', 'test.js']

stages:
  dev:
    host: 0.0.0.0
    port: 2222

scripts:
  logs: 'pm2 logs'
  install: yarn
  build: yarn build
  status_check: 'pm2 info api'
  start: 'pm2 start pm2.config.js'
  stop: 'pm2 stop pm2.config.js'
  reload: 'pm2 reload pm2.config.js'
  list_services: 'pm2 list pm2.config.js'

notifications:
  slack:
    enabled: true
    endpoint: ${BOSS_TEST_SLACK_CHANNEL} 

